language: python
services:
  - docker
python:
  - "2.7"
install:
  - make deps
script:
  - make lint
  - make test_xunit
  - make docker_build
  - make docker_push
deploy:
  provider: heroku
  app: mighty-thicket-74575
  api_key: ${HEROKU_API_KEY}
